# Sistemas lineares - Aula 3

## Eliminação de Gauss com pivoteamento parcial
O que acontece quando o pivô é zero ou muito próximo de zero?
Como você usa o pivô para zerar todos os valores abaixo dele, se ele for zero é difícil ou impossível de zerar sua coluna.

### Estratégia de pivoteamento parcial
1. A cada passo K, antes da etapa de eliminação (antes de zerar todo mundo da coluna), encontre $p$ no intervalo $[k,n]$ tal que $|a_{pk}^{(k)} = max\{|a_{1k}^{(k)}|\}$
2. Permute as linhas p e k (Implementação: exercício da lista)


* **Como ficaria a fatoração LU agora que sabemos fazer pivoteamento?** $P\cdot A = L\cdot U$, onde $P$ uma matriz de permutação.

#### Teorema
Se $A \in M_n(\mathbb{R})$ é invertível, então existe uma única decomposição $P\cdot A = L\cdot U, det(A) = (-1)^p\prod_{i=1}^{n}u_{ii}$, onde $p$ é o número de permutações de $A$

Resolvendo $A\cdot x = b$
$(L\cdot U)\cdot x = (P\cdot A)\cdot x = P\cdot b$

* $L\cdot y = P\cdot b$ (substituições progressivas)
* $U\cdot x = y$ (substituições regressivas)

**Implementação:** exercício.

### Métodos diretos
* Fatoração LU
* Eliminação de Gauss

### Métodos iterativos
* $x_0, x_1, \cdots, x_{(k)}$, com $x_{(k)} \leftrightarrow x$ solução do sistema $A\cdot x = b$.

## Cálculo da inversa de uma matriz
Seja $A \in M_n(\mathbb{R})$ uma matriz não singular. Vamos calcular a inversa de $A$, isto é, $A^{-1} = 
\begin{bmatrix}
v_1  \cdots  v_n
\end{bmatrix}$, em que $v_i$ é a i-ésima coluna de A.  
Portanto, $A\cdot A_i = I$.  
$A\cdot \begin{bmatrix}
v_1  \cdots  v_n
\end{bmatrix} = \begin{bmatrix}
e_1  \cdots  e_n
\end{bmatrix}$  
Portanto, basta resolver n sistemas lineares $A\cdot v_i = e_i, i = 1, \cdots, n$

### Implementação
Calcular a inversa de uma matriz A qualquer.
* Fatoração LU de A (def lu)
* Depois resolver n sistema $A\cdot v_i = e_i$ (def triang sup e def triang inf)
* $A^{-1} = \begin{bmatrix}
v_1  \cdots  v_n
\end{bmatrix}$ (def inv)

In [13]:
import numpy as np

# Fatoração LU
def LU_factor(A): 
    n = np.shape(A)[0]
    U = np.zeros((n, n))
    L = np.eye(n)
    
    for i in np.arange(n):
        for j in np.arange(i, n):
            L[j, i] = A[j, i]
            U[i, j] = A[i, j]
            for k in np.arange(i):
                U[i, j] -= L[i, k] * U[k, j]
                L[j, i] -= L[j, k] * U[k, i]
            L[j, i] /= U[i, i]
    
    return L, U       

# Main program
A = np.array([[1, 2,0], [1, 3,1],[-2, 0,1]])
L, U = LU_factor(A)   
print (L)
print (U)

[[ 1.  0.  0.]
 [ 1.  1.  0.]
 [-2.  4.  1.]]
[[ 1.  2.  0.]
 [ 0.  1.  1.]
 [ 0.  0. -3.]]
